# Generated by Django 5.2.17 on 2026-08-25 04:55

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Shared login address for this body.', max_length=254, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('acronym', models.CharField(help_text="Prefix for this body's reference codes.", max_length=20)),
                ('type', models.CharField(default='Committee', max_length=30)),
                ('campus', models.CharField(blank=True, max_length=50)),
                ('last_seq', models.PositiveIntegerField(default=0, help_text="Reference-code counter. Managed by the engine — don't edit.")),
                ('logo', models.CharField(blank=True, help_text='Filename under static/logos/, or a full URL.', max_length=300)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PointsScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinator_points', models.IntegerField(default=20)),
                ('domain_task_points', models.IntegerField(default=10)),
                ('vetter_points', models.IntegerField(default=10)),
                ('early_window_hours', models.IntegerField(default=24, help_text='Finish within this many hours to earn the early bonus.')),
                ('early_bonus_pct', models.IntegerField(default=30)),
                ('late_threshold_hours', models.IntegerField(default=48, help_text='Past this many hours, the late penalty starts.')),
                ('late_penalty_pct', models.IntegerField(default=30)),
                ('subsequent_delay_hours', models.IntegerField(default=6, help_text='Each further block of this many hours adds another penalty step.')),
                ('subsequent_penalty_pct', models.IntegerField(default=10)),
            ],
            options={
                'verbose_name': 'point scheme',
                'verbose_name_plural': 'point scheme',
            },
        ),
        migrations.CreateModel(
            name='PortalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sla_hours', models.PositiveIntegerField(default=48, help_text='Coverage requests for events starting within this many hours are held for POC approval.')),
                ('strike_limit', models.PositiveIntegerField(default=3, help_text='A member at or above this many strikes stops being eligible for new assignments.')),
                ('campus_strict', models.BooleanField(default=True, help_text='Only assign members from the same campus as the requesting body.')),
                ('require_approval_always', models.BooleanField(default=False, help_text='Hold every request for POC approval, not just short-notice ones.')),
                ('strike_assignee_too', models.BooleanField(default=False, help_text='On a missed deadline, strike the assignee as well as the coordinator.')),
                ('secretary_emails', models.JSONField(blank=True, default=list, help_text='Secretary / POC accounts. Approve or reject gated requests, manage the roster.')),
                ('admin_emails', models.JSONField(blank=True, default=list, help_text='Admin accounts. Everything a secretary can do, plus editing the point scheme.')),
                ('allowed_domains', models.JSONField(blank=True, default=list, help_text='Email domains permitted to sign in, e.g. ["iimsirmaur.ac.in"].')),
                ('head_email', models.EmailField(blank=True, help_text='Copied on late-task notifications.', max_length=254)),
                ('committee_name', models.CharField(default='Media & Communications Committee', max_length=200)),
                ('default_acronym', models.CharField(default='MEDIA', help_text="Reference-code prefix for requests from accounts that aren't a registered committee.", max_length=20)),
                ('general_seq', models.PositiveIntegerField(default=0, help_text="Counter behind MEDIA_n reference codes. Managed by the engine — don't edit.")),
            ],
            options={
                'verbose_name': 'portal settings',
                'verbose_name_plural': 'portal settings',
            },
        ),
        migrations.CreateModel(
            name='PostSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(unique=True)),
            ],
            options={
                'ordering': ['time'],
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_code', models.CharField(blank=True, db_index=True, help_text='Human-readable ID, e.g. SPT_12.', max_length=50)),
                ('type', models.CharField(choices=[('Coverage', 'Coverage'), ('Post', 'Post')], max_length=20)),
                ('status', models.CharField(choices=[('New', 'New'), ('Pending for POC approval', 'Pending for POC approval'), ('Request Accepted', 'Request Accepted'), ('Event Covered', 'Event Covered'), ('Ready To post', 'Ready To post'), ('Posted', 'Posted'), ('Rejected', 'Rejected')], db_index=True, default='New', max_length=40)),
                ('event_name', models.CharField(max_length=300)),
                ('event_start', models.DateTimeField(blank=True, null=True)),
                ('event_end', models.DateTimeField(blank=True, null=True)),
                ('venue', models.CharField(blank=True, max_length=300)),
                ('requester', models.CharField(blank=True, help_text='Person raising it, free text.', max_length=200)),
                ('contact_email', models.EmailField(db_index=True, help_text='The signed-in account that submitted it.', max_length=254)),
                ('campus', models.CharField(blank=True, max_length=50)),
                ('roles_needed', models.JSONField(blank=True, default=list)),
                ('platforms', models.JSONField(blank=True, default=list)),
                ('content_links', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('coordinator_email', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('roster', models.JSONField(blank=True, default=list, help_text='Contact-facing assignees, as sent to the requester.')),
                ('posts', models.JSONField(blank=True, default=list, help_text='Per-platform scheduling outcome.')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('decision_by', models.EmailField(blank=True, max_length=254)),
                ('decision_at', models.DateTimeField(blank=True, null=True)),
                ('reject_reason', models.TextField(blank=True)),
                ('ready_by', models.EmailField(blank=True, max_length=254)),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=100, unique=True)),
                ('required_skill', models.CharField(help_text='A member needs this skill to be eligible.', max_length=100)),
                ('points', models.IntegerField(default=0)),
                ('sla_hours', models.PositiveIntegerField(default=0, help_text='Hours after the event ends (or after submission) that this task is due. 0 = due at event end.')),
                ('at_event', models.BooleanField(default=False, help_text="Performed during the event itself, so the assignee's calendar is checked for clashes.")),
                ('requestable', models.BooleanField(default=False, help_text='A committee can ask for this role on the New Request form.')),
                ('internal_assignable', models.BooleanField(default=False, help_text='Staff can add this task to a request manually.')),
                ('vertical', models.CharField(blank=True, help_text='Scopes which domain head may assign it. Blank = unscoped.', max_length=50)),
            ],
            options={
                'ordering': ['task'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('skills', models.JSONField(blank=True, default=list, help_text="Matched against a task type's required skill.")),
                ('vertical', models.CharField(blank=True, max_length=50)),
                ('year', models.PositiveSmallIntegerField(default=1, help_text='Academic year. Second-years may assign tasks anywhere.')),
                ('campus', models.CharField(blank=True, max_length=50)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('active', models.BooleanField(default=True)),
                ('points', models.IntegerField(default=0)),
                ('strikes', models.IntegerField(default=0)),
                ('domain_head_of', models.CharField(blank=True, help_text='Vertical this member heads, granting manual-assign rights within it. Blank = not a head.', max_length=50)),
                ('availability', models.CharField(choices=[('available', 'On work'), ('out', 'Out of work')], default='available', max_length=20)),
                ('availability_changed_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the current availability state began.')),
                ('on_work_days', models.FloatField(default=0.0, help_text='Banked days on work.', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('out_days', models.FloatField(default=0.0, help_text='Banked days out of work.', validators=[django.core.validators.MinValueValidator(0.0)])),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=50)),
                ('handler_email', models.EmailField(help_text='Who publishes to this channel. Scheduled posts are assigned to them.', max_length=254)),
                ('points', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['platform', 'handler_email'],
                'constraints': [models.UniqueConstraint(fields=('platform', 'handler_email'), name='unique_platform_handler')],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('event', models.CharField(db_index=True, max_length=50)),
                ('ref_code', models.CharField(blank=True, max_length=50)),
                ('actor', models.CharField(blank=True, help_text="Who caused it, or 'engine'.", max_length=200)),
                ('member', models.CharField(blank=True, help_text='Who it happened to.', max_length=200)),
                ('detail', models.CharField(blank=True, max_length=500)),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity', to='core.request')),
            ],
            options={
                'verbose_name': 'activity log entry',
                'verbose_name_plural': 'activity log',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req_type', models.CharField(max_length=20)),
                ('ref_code', models.CharField(blank=True, db_index=True, max_length=50)),
                ('task', models.CharField(max_length=100)),
                ('required_skill', models.CharField(blank=True, max_length=100)),
                ('at_event', models.BooleanField(default=False)),
                ('vertical', models.CharField(blank=True, db_index=True, max_length=50)),
                ('platform', models.CharField(blank=True, max_length=50)),
                ('member', models.CharField(blank=True, help_text="Assignee's display name.", max_length=200)),
                ('email', models.EmailField(blank=True, db_index=True, help_text='Assignee.', max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('points', models.IntegerField(default=0)),
                ('points_awarded', models.BooleanField(default=False, help_text="Engine flag: base points already credited. Don't edit.")),
                ('timing_applied', models.BooleanField(default=False, help_text="Engine flag: completion-timing modifier already applied. Don't edit.")),
                ('struck', models.BooleanField(default=False, help_text="Engine flag: a strike was already issued for this task. Don't edit.")),
                ('status', models.CharField(choices=[('PROPOSED', 'PROPOSED'), ('CONFIRMED', 'CONFIRMED'), ('DONE', 'DONE'), ('LATE', 'LATE'), ('UNFILLED', 'UNFILLED'), ('SCHEDULED', 'SCHEDULED')], db_index=True, default='PROPOSED', max_length=20)),
                ('reason', models.CharField(blank=True, help_text='Why this task is UNFILLED, when it is.', max_length=300)),
                ('deadline', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('scheduled_at', models.DateTimeField(blank=True, help_text='Post tasks only.', null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('coordinator_email', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('event_name', models.CharField(blank=True, max_length=300)),
                ('event_start', models.DateTimeField(blank=True, null=True)),
                ('event_end', models.DateTimeField(blank=True, null=True)),
                ('venue', models.CharField(blank=True, max_length=300)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.request')),
            ],
            options={
                'ordering': ['deadline', 'task'],
                'indexes': [models.Index(fields=['status', 'deadline'], name='core_task_status_c090db_idx')],
            },
        ),
    ]
