# Generated by Django 5.2.17 on 2026-09-28 20:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portalsettings',
            name='strike_assignee_too',
        ),
        migrations.RemoveField(
            model_name='portalsettings',
            name='strike_limit',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='strikes',
        ),
        migrations.AddField(
            model_name='request',
            name='supervisor_email',
            field=models.EmailField(blank=True, db_index=True, help_text='The Task Supervisor (Coverage only). Only staff can change it.', max_length=254),
        ),
        migrations.AddField(
            model_name='teammember',
            name='red_strikes',
            field=models.IntegerField(default=0, help_text='Serious strikes. Given manually by POC/Admin.'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='secondary_vertical',
            field=models.CharField(blank=True, help_text='Second vertical they can also work in. Tried after the primary-vertical members.', max_length=50),
        ),
        migrations.AddField(
            model_name='teammember',
            name='yellow_strikes',
            field=models.IntegerField(default=0, help_text='Warnings. Given manually; never block work.'),
        ),
        migrations.AlterField(
            model_name='task',
            name='struck',
            field=models.BooleanField(default=False, help_text="Engine flag: this task was already marked LATE by the deadline sweep. Don't edit."),
        ),
        migrations.AlterField(
            model_name='tasktype',
            name='required_skill',
            field=models.CharField(blank=True, help_text='A member needs this skill to be eligible. Blank = no skill needed.', max_length=100),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='vertical',
            field=models.CharField(blank=True, help_text='Primary vertical. Auto-assignment tries these members first.', max_length=50),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='year',
            field=models.PositiveSmallIntegerField(default=1, help_text='Academic year. Second-years are only ever Task Supervisors; first-years do the work.'),
        ),
        migrations.CreateModel(
            name='SubEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('venue', models.CharField(blank=True, max_length=300)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_events', to='core.request')),
            ],
            options={
                'ordering': ['start', 'pk'],
                'constraints': [models.CheckConstraint(condition=models.Q(('end__gt', models.F('start'))), name='subevent_end_after_start')],
            },
        ),
    ]
