# Generated by Django 5.2.17 on 2026-09-29 15:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_task_supervisor_and_coordinator_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='paired_task',
            field=models.ForeignKey(blank=True, help_text='On an editing task: the shooter task whose work it edits. The editor follows the shooter when the shooter is reassigned.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paired_editors', to='core.task'),
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('venue', models.CharField(blank=True, help_text='May be blank if the MOM person is booking it.', max_length=300)),
                ('agenda', models.TextField(blank=True)),
                ('called_by', models.EmailField(db_index=True, help_text='Who called the meeting.', max_length=254)),
                ('wants_mom', models.BooleanField(default=False, help_text='The caller asked for someone to take minutes and book the venue.')),
                ('mom_email', models.EmailField(blank=True, help_text='Who takes the minutes and books the venue. Responsibility only: no points.', max_length=254)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-start', '-pk'],
                'constraints': [models.CheckConstraint(condition=models.Q(('end__gt', models.F('start'))), name='meeting_end_after_start')],
            },
        ),
        migrations.CreateModel(
            name='MeetingInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance', models.CharField(blank=True, choices=[('', 'Not marked'), ('present', 'Present'), ('late', 'Late'), ('absent', 'Absent'), ('excused', 'Excused')], default='', max_length=10)),
                ('strike_given', models.BooleanField(default=False, help_text="Engine flag: marking this person Absent gave them a yellow strike. Don't edit.")),
                ('marked_by', models.EmailField(blank=True, max_length=254)),
                ('marked_at', models.DateTimeField(blank=True, null=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='core.meeting')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_invites', to='core.teammember')),
            ],
            options={
                'ordering': ['member__name'],
                'constraints': [models.UniqueConstraint(fields=('meeting', 'member'), name='unique_invite_per_meeting')],
            },
        ),
    ]
