# Generated by Django 5.2.17 on 2026-09-30 13:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_meetings_and_paired_editors'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(help_text='The last day out; they return the day after.')),
                ('status', models.CharField(choices=[('pending', 'Waiting for approval'), ('approved', 'Approved'), ('rejected', 'Declined'), ('cancelled', 'Withdrawn'), ('ended', 'Ended')], db_index=True, default='pending', max_length=10)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('decided_by', models.EmailField(blank=True, max_length=254)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, help_text='Engine: when the member was actually switched to Out of work.', null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='core.teammember')),
            ],
            options={
                'ordering': ['-requested_at', '-pk'],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='leave_end_not_before_start')],
            },
        ),
    ]
