# Generated by Django 5.2.17 on 2026-09-30 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_retime_event_coordinators'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='is_multiday',
            field=models.BooleanField(default=False, help_text='A multi-day Coverage event: only a start and end *date* were given, so it runs from the start of the first day to the end of the last, has no single venue (each sub-event has its own) and no calendar holds.'),
        ),
    ]
