# Generated by Django 5.2.17 on 2026-10-03 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_multiday_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='created_on_behalf_by',
            field=models.EmailField(blank=True, help_text="Set when the POC/Admin entered this request for a club that hadn't (then `contact_email` is the club's login). Blank for a request the club raised itself.", max_length=254),
        ),
    ]
