# Generated by Django 5.2.17 on 2026-10-08 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_request_created_on_behalf_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='sub_event',
            field=models.ForeignKey(blank=True, help_text="Set when this task covers one sub-event of a multi-day event (its own photographer/videographer and their editing). Its event times, venue and deadline are that sub-event's, not the whole event's.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='core.subevent'),
        ),
    ]
