# Generated by Django 5.2.17 on 2026-10-08 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_task_sub_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='co_coordinator_email',
            field=models.EmailField(blank=True, db_index=True, help_text="An additional Event Coordinator (Coverage only), added by the POC/Admin. They have all the main coordinator's powers; `coordinator_email` stays the main one.", max_length=254),
        ),
        migrations.AddField(
            model_name='task',
            name='additional',
            field=models.BooleanField(default=False, help_text="On an Event Coordinator task: this is the request's additional coordinator, not the main one."),
        ),
    ]
